name: Version Increment

on: pull_request

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: sudo apt-get install jq

    - name: Fetch main branch
      run: git fetch origin main:refs/remotes/origin/main

    - name: Increment package.json version if needed
      run: |
        BASE_VERSION=$(git show origin/main:package.json | jq -r '.version')
        PR_VERSION=$(jq -r '.version' package.json)
        
        if [ "$BASE_VERSION" == "$PR_VERSION" ]; then
          NEW_VERSION=$(echo $PR_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          jq ".version = \"$NEW_VERSION\"" package.json > temp.json && mv temp.json package.json
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json
          git commit -m "Bump package.json version to $NEW_VERSION"
          git push
        else
          echo "Version already updated."
        fi